/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Counter: (() => {
      const tableId = new TableId("", "Counter");
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    SecurityCounter: (() => {
      const tableId = new TableId("", "SecurityCounter");
      return defineComponent(
        world,
        {
          value: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Locked: (() => {
      const tableId = new TableId("", "Locked");
      return defineComponent(
        world,
        {
          value: RecsType.Boolean,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Future: (() => {
      const tableId = new TableId("", "Future");
      return defineComponent(
        world,
        {
          is: RecsType.Boolean,
          expiry: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Swap: (() => {
      const tableId = new TableId("", "Swap");
      return defineComponent(
        world,
        {
          is: RecsType.Boolean,
          rate: RecsType.BigInt,
          index: RecsType.String,
          margin: RecsType.BigInt,
          expiry: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Option: (() => {
      const tableId = new TableId("", "Option");
      return defineComponent(
        world,
        {
          is: RecsType.Boolean,
          strike: RecsType.BigInt,
          expiry: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
