// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Character, CharacterData, CharacterTableId } from "./tables/Character.sol";
import { CharacterSec, CharacterSecData, CharacterSecTableId } from "./tables/CharacterSec.sol";
import { Strength, StrengthTableId } from "./tables/Strength.sol";
import { Intelligence, IntelligenceTableId } from "./tables/Intelligence.sol";
import { Zen, ZenTableId } from "./tables/Zen.sol";
import { Special, SpecialTableId } from "./tables/Special.sol";
import { Base, BaseTableId } from "./tables/Base.sol";
import { Locked, LockedTableId } from "./tables/Locked.sol";
import { Factory, FactoryTableId } from "./tables/Factory.sol";
import { Owner, OwnerTableId } from "./tables/Owner.sol";
import { Security, SecurityData, SecurityTableId } from "./tables/Security.sol";
import { Collateral, CollateralTableId } from "./tables/Collateral.sol";
import { Committed, CommittedTableId } from "./tables/Committed.sol";
import { Held, HeldTableId } from "./tables/Held.sol";
import { Principal, PrincipalTableId } from "./tables/Principal.sol";
import { FixedRate, FixedRateTableId } from "./tables/FixedRate.sol";
import { FloatingRate, FloatingRateTableId } from "./tables/FloatingRate.sol";
import { Expiry, ExpiryTableId } from "./tables/Expiry.sol";
import { Price, PriceTableId } from "./tables/Price.sol";
import { Strike, StrikeTableId } from "./tables/Strike.sol";
import { Frequency, FrequencyTableId } from "./tables/Frequency.sol";
import { FrequencyLastPaid, FrequencyLastPaidTableId } from "./tables/FrequencyLastPaid.sol";
