// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Character, CharacterData, CharacterTableId } from "./tables/Character.sol";
import { Strength, StrengthTableId } from "./tables/Strength.sol";
import { Intelligence, IntelligenceTableId } from "./tables/Intelligence.sol";
import { Zen, ZenTableId } from "./tables/Zen.sol";
import { Special, SpecialTableId } from "./tables/Special.sol";
import { Base, BaseTableId } from "./tables/Base.sol";
import { Locked, LockedTableId } from "./tables/Locked.sol";
import { Factory, FactoryTableId } from "./tables/Factory.sol";
import { Future, FutureData, FutureTableId } from "./tables/Future.sol";
import { Swap, SwapData, SwapTableId } from "./tables/Swap.sol";
import { Option, OptionData, OptionTableId } from "./tables/Option.sol";
