// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISecuritizeSystem {
  function generateSecurity() external returns (bytes32 id);
}
