// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISecuritizeSystem {
  function generateCompleteSecurity(
    bytes32 _underlyingId,
    uint256 _principal,
    uint256 _price,
    uint256 _floatRate,
    uint256 _fixedRate,
    uint256 _expiry,
    uint256 _frequency,
    uint256 _strike
  ) external returns (bytes32 secId);

  function generateSecurity(bytes32 _underlyingId) external returns (bytes32 id);

  function commitSecurity(bytes32 _id) external;

  function enterSecurity(bytes32 _id) external;

  function unwindSecurity(bytes32 _id) external;

  function addPrincipal(bytes32 _id, uint256 _principal) external;

  function addPrice(bytes32 _id, uint256 _price) external;

  function addFixedRate(bytes32 _id, uint256 _rate) external;

  function addFloatingRate(bytes32 _id, uint256 _rate) external;

  function addExpiry(bytes32 _id, uint256 _fromNow) external;

  function addFrequency(bytes32 _id, uint256 _frequency) external;

  function addStrike(bytes32 _id, uint256 _strike) external;
}
