// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITokenizeSystem {
  function tokenizeEntity(bytes32 _id, string calldata _uri) external;

  function redeemEntity(uint256 _tokenId) external;

  function claimToken(uint256 _tokenId) external;
}
