// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IDemoEntitySystem } from "./IDemoEntitySystem.sol";
import { IIncrementSystem } from "./IIncrementSystem.sol";
import { ITokenizeSystem } from "./ITokenizeSystem.sol";
import { ITradeSystem } from "./ITradeSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is IBaseWorld, IDemoEntitySystem, IIncrementSystem, ITokenizeSystem, ITradeSystem {
    //event Transfer(address indexed _from, address indexed _to, uint256 indexed _tokenId);
}
