// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IDemoEntitySystem } from "./IDemoEntitySystem.sol";
import { ISecuritizeSystem } from "./ISecuritizeSystem.sol";
import { ITokenizeSystem } from "./ITokenizeSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is IBaseWorld, IDemoEntitySystem, ISecuritizeSystem, ITokenizeSystem {

}
